# Generated by Django 5.1 on 2025-05-27 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Barcode')),
                ('product_type', models.CharField(blank=True, max_length=100, verbose_name='Product Type')),
                ('option1_name', models.CharField(blank=True, max_length=100, verbose_name='Option 1 Name')),
                ('option1_value', models.CharField(blank=True, max_length=100, verbose_name='Option 1 Value')),
                ('option2_name', models.CharField(blank=True, max_length=100, verbose_name='Option 2 Name')),
                ('option2_value', models.CharField(blank=True, max_length=100, verbose_name='Option 2 Value')),
                ('buying_price', models.IntegerField(blank=True, null=True, verbose_name='Buying Price')),
                ('selling_price', models.IntegerField(blank=True, null=True, verbose_name='Selling Price')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, to='core.tag')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vendor')),
            ],
        ),
    ]
