# Generated by Django 5.1 on 2025-05-27 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='database_allproducts',
        ),
    ]
