# Generated by Django 5.1 on 2025-05-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_inventoryitem_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='stock_units',
            field=models.IntegerField(),
        ),
    ]
