from django.urls import path
from . import views
from .views import admin_dashboard

urlpatterns = [
    path('', views.dashboard, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('notifications/', views.notifications, name='notifications'),
    path('products/', views.products, name='products'),
    path('products/add/', views.add_product, name='add_product'),
    path('categories/', views.categories, name='categories'),
    path('inventory/planner/', views.inventory_planner, name='inventory_planner'),
    path('inventory/stock-movement/', views.stock_movement, name='stock_movement'),
    path('sales/insights/', views.sales_insights, name='sales_insights'),
    path('sales/pricing/', views.pricing_strategies, name='pricing_strategies'),
    path('sales/comparison/', views.store_comparison, name='store_comparison'),
    path('transfer/request/', views.request_items, name='request_items'),
    path('transfer/shipments/', views.shipments_tracking, name='shipments_tracking'),
    path('transfer/delivery/', views.delivery_status, name='delivery_status'),
    path('reports/', views.reports, name='reports'),
    path('reports/market-trends/', views.market_trends, name='market_trends'),
    path('reports/custom/', views.custom_reports, name='custom_reports'),
    path('market/competitor/', views.competitor_analysis, name='competitor_analysis'),
    path('market/vendor/', views.vendor_management, name='vendor_management'),
    path('business/health/', views.business_health, name='business_health'),
    path('business/trend-tracker/', views.trend_tracker, name='trend_tracker'),
    path('system/performance/', views.performance_metrics, name='performance_metrics'),
    path('system/diagnostics/', views.technical_diagnostics, name='technical_diagnostics'),
    path('team/management/', views.team_management, name='team_management'),
    path('team/activity-log/', views.activity_log, name='activity_log'),
    path('team/workforce/', views.workforce_planner, name='workforce_planner'),
    path('training/tutorials/', views.system_tutorials, name='system_tutorials'),
    path('training/staff/', views.staff_training, name='staff_training'),
    path('customer/feedback/', views.feedback_tracker, name='feedback_tracker'),
    path('customer/loyalty/', views.loyalty_program, name='loyalty_program'),
    path('help/user-guide/', views.user_guide, name='user_guide'),
    path('help/support/', views.support_center, name='support_center'),
    path('settings/', views.settings, name='settings'),
    path('messages/incoming-tasks/', views.incoming_tasks, name='incoming_tasks'),
    path('messages/system-notifications/', views.system_notifications, name='system_notifications'),
    path('tasks/scheduler/', views.task_scheduler, name='task_scheduler'),
    path('tasks/promotion-calendar/', views.promotion_calendar, name='promotion_calendar'),
]